### ISSUE TITLE
RuntimeException when trying to solve Hanoi Tower instance 1 with deterministic BerkMin

### ISSUE THREAD

**Issue by rtaupe** [AntoniusW/Alpha#35]
In d1e9b64c7cae1a37a54de889cb49a18223d4f80b, test cases for four different instances of the [Tower of Hanoi problem](https://www.mat.unical.it/aspcomp2013/HanoiTower) are added to the project.
By this, a bug can be discovered that causes a RuntimeException to be thrown by `at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.propagate()` when the `deterministic BerkMin` heuristic is employed:

> java.lang.RuntimeException: Assignment entry is for current decision level but marked as reassign at lower one. Should not happen.
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.propagate(BasicNoGoodStore.java:632)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:104)
> 	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)

**Comment by rtaupe** [comment]
After changes by @AntoniusW I now get a different exception:

> java.lang.RuntimeException: Processing Re-assignment of entry for TRUE, but encountered a NoGood where alpha propagation was not done. Should not happen.
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.ensureWatchInvariantAfterAssignAtLowerDL(BasicNoGoodStore.java:533)
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.propagate(BasicNoGoodStore.java:632)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:112)
> 	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)

**Comment by AntoniusW** [comment]
With fbc723b merged (locally) into testing-hanoi, I no longer see this exception, even with increased timeout.
Can you verify whether the bug is still there?

**Comment by rtaupe** [comment]
At the moment I cannot reproduce the exact same Exception , but a similar one:

> java.lang.RuntimeException: Processing re-assignment of an entry, but encountered a NoGood where unit propagation was not done. Should not happen.
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.ensureWatchInvariantAfterAssignAtLowerDL(BasicNoGoodStore.java:423)
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.propagate(BasicNoGoodStore.java:650)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:119)
> 	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)

Can be reproduced with `at.ac.tuwien.kr.alpha.solver.HanoiTowerTest.testInstance4()`, `BerkMinLiteral`, `seed=239464990387691`.

**Comment by AntoniusW** [comment]
With the latest bugfixes, it seems the error is gone. Can you verify or report if another exception is thrown?

**Comment by rtaupe** [comment]
I still can reproduce the Exception with the exact same configuration. How strange that you cannot ...

> java.lang.RuntimeException: Processing re-assignment of an entry, but encountered a NoGood where unit propagation was not done. Should not happen.
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.ensureWatchInvariantAfterAssignAtLowerDL(BasicNoGoodStore.java:423)
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.propagate(BasicNoGoodStore.java:650)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:121)
> 	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)

**Comment by rtaupe** [comment]
After rebasing the testing-hanoi branch on master, it is currently not possible to check whether this bug still occurs, because the solver does not terminate in any reasonable amount of time on the relevant test case.
